Repository Step3-kakao-tech-campus/Team4_FE, pull requests merged in 2023-11, with the labels that each got.

#87 음식점 상세 페이지 후기 요약 추가
  src/apis/storeDetail.ts
  src/components/organisms/storeDetailTab.tsx
  src/components/organisms/storeOverviewTab.tsx
  src/components/template/storeDetailTemplate.tsx
  src/hooks/query.ts
  src/i18n.js
  src/mocks/handlers.ts
  src/types/review.ts
  src/types/store.ts
Labels: enhancement

#90 모달 커스텀 훅 수정
  src/components/modals/deleteReviewModal.tsx
  src/components/modals/languageModal.tsx
  src/components/modals/modalContainer.tsx
  src/components/modals/searchModal.tsx
  src/components/modals/socialLoginModalContent.tsx
  src/components/page/reviewDetailPage.tsx
  src/hooks/modal.ts
  src/store/slices/modalSlice.ts
Labels: bug

#88 Error Boundary 구현
  src/App.tsx
  src/components/atoms/globalLoader.tsx
  src/components/layouts/errorBoundary.tsx
  src/components/page/errorPage.tsx
  src/components/page/notFoundPage.tsx
  src/components/page/storeDetailPage.tsx
  src/i18n.js
  src/mocks/handlers.ts
  src/utils/query.ts
Labels: enhancement

#92 (회원가입) 유저 정보 입력 페이지 구현
  src/App.tsx
  src/apis/profile.ts
  src/components/molecules/pageTitleCard.tsx
  src/components/organisms/editProfileForm.tsx
  src/components/page/registerUserInfoPage.tsx
  src/components/template/registerUserInfoTemplate.tsx
  src/i18n.js
  src/mocks/handlers.ts
Labels: enhancement

#91 소셜 로그인 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/socialLoginButton.tsx
  src/components/page/loginRedriect.tsx
  src/mocks/handlers.ts
  src/utils/fetch.ts
Labels: enhancement

#99 로그인 레이아웃 구현
  src/App.tsx
  src/components/atoms/button.tsx
  src/components/atoms/socialLoginButton.tsx
  src/components/layouts/login.tsx
  src/components/page/coinRechargePage.tsx
  src/components/page/coinUsagePage.tsx
  src/components/page/likedReviewPage.tsx
  src/components/page/likedStorePage.tsx
  src/components/page/promptPage.tsx
  src/components/page/recentlyViewdStorePage.tsx
  src/components/page/registerUserInfoPage.tsx
  src/components/page/userEditProfilePage.tsx
  src/components/page/userPage.tsx
  src/components/page/writeReviewPage.tsx
  src/components/page/writedReviewPage.tsx
Labels: enhancement

#97 PageTitleCard 컴포넌트 뒤로가기 버튼 삭제
  src/components/molecules/pageTitleCard.tsx
  src/components/template/registerUserInfoTemplate.tsx
  src/i18n.js
Labels: enhancement

#105 리뷰 삭제 기능 구현
  src/apis/review.ts
  src/components/atoms/socialLoginButton.tsx
  src/components/layouts/login.tsx
  src/components/modals/deleteReviewModal.tsx
  src/components/modals/modalContainer.tsx
  src/components/molecules/reviewInformation.tsx
  src/components/organisms/reviewImageCarousel.tsx
  src/components/page/loginRedriect.tsx
  src/components/template/reviewDetailTemplate.tsx
  src/i18n.js
  src/types/review.ts
Labels: enhancement

#113 소셜 로그인 버튼 가운데 정렬
  src/components/atoms/socialLoginButton.tsx
  src/components/layouts/login.tsx
Labels: Applied feedback

#115 API 명세에 맞게 코드 수정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/instance.ts
  src/apis/map.ts
  src/apis/review.ts
  src/apis/search.ts
  src/apis/storeDetail.ts
  src/components/atoms/image.tsx
  src/components/modals/searchModal.tsx
  src/components/molecules/marker.tsx
  src/components/molecules/reviewCard.tsx
  src/components/molecules/reviewInformation.tsx
  src/components/molecules/storeCard.tsx
  src/components/organisms/MyGoogleMap.tsx
  src/components/organisms/storeDetailTab.tsx
  src/components/organisms/storeOverviewTab.tsx
  src/components/organisms/storeReviewTab.tsx
  src/components/page/errorPage.tsx
  src/components/page/reviewDetailPage.tsx
  src/components/page/searchResultPage.tsx
  src/components/page/storeDetailPage.tsx
  src/components/template/likedReviewTemplate.tsx
  src/components/template/likedStoreTemplate.tsx
  src/components/template/recentlyViewdStoreTemplate.tsx
  src/components/template/reviewDetailTemplate.tsx
  src/components/template/searchResultTemplate.tsx
  src/components/template/storeDetailTemplate.tsx
  src/components/template/writedReviewTemplate.tsx
  src/hooks/convert.ts
  src/hooks/modal.ts
  src/hooks/query.ts
  src/i18n.js
  src/mocks/data/coinData.js
  src/mocks/data/prompts.js
  src/mocks/data/recentlyViewdStore.js
  src/mocks/data/reviewDetailData.js
  src/mocks/data/storeMarker.js
  src/mocks/data/writedReview.js
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/setupProxy.js
  src/types/map.ts
  src/types/response.ts
  src/types/review.ts
  src/types/store.ts
  src/utils/convert.ts
Labels: refactor

#117 config: 로그인 로직 수정
  src/App.tsx
  src/apis/profile.ts
  src/components/atoms/socialLoginButton.tsx
  src/components/page/loginRedriect.tsx
Labels: enhancement

#116 리뷰 내용 번역 기능 구현
  src/apis/translate.ts
  src/components/layouts/login.tsx
  src/components/organisms/MyGoogleMap.tsx
  src/components/template/reviewDetailTemplate.tsx
  src/setupProxy.js
Labels: enhancement

#120 API 명세에 맞게 코드 수정 및 기타 개선
  public/blankImages/cake.svg
  public/blankImages/cocktail.svg
  public/blankImages/coffee.svg
  public/blankImages/cutlery.svg
  public/blankImages/fastfood.svg
  public/blankImages/restaurantplate.svg
  public/blankImages/soup.svg
  public/blankImages/wine.svg
  src/App.tsx
  src/apis/checkLike.ts
  src/apis/coin.ts
  src/apis/getPresignedUrl.ts
  src/apis/likedStore.ts
  src/apis/map.ts
  src/apis/review.ts
  src/apis/translate.ts
  src/apis/uploadImageToS3.ts
  src/components/atoms/icon.tsx
  src/components/atoms/image.tsx
  src/components/layouts/login.tsx
  src/components/layouts/navigationBar.tsx
  src/components/molecules/coinListCard.tsx
  src/components/molecules/marker.tsx
  src/components/molecules/reviewCard.tsx
  src/components/molecules/reviewInformation.tsx
  src/components/molecules/storeCard.tsx
  src/components/molecules/storeDetailHeader.tsx
  src/components/organisms/MyGoogleMap.tsx
  src/components/organisms/storeReviewTab.tsx
  src/components/page/coinRechargePage.tsx
  src/components/page/coinUsagePage.tsx
  src/components/page/likedReviewPage.tsx
  src/components/page/likedStorePage.tsx
  src/components/page/loginRedriect.tsx
  src/components/page/mainPage.tsx
  src/components/page/promptPage.tsx
  src/components/page/recentlyViewdStorePage.tsx
  src/components/page/recentlyViewedStorePage.tsx
  src/components/page/registerUserInfoPage.tsx
  src/components/page/userEditProfilePage.tsx
  src/components/page/userPage.tsx
  src/components/page/writeReviewPage.tsx
  src/components/page/writedReviewPage.tsx
  src/components/template/coinRechargeTemplate.tsx
  src/components/template/coinUsageTemplate.tsx
  src/components/template/likedReviewTemplate.tsx
  src/components/template/likedStoreTemplate.tsx
  src/components/template/recentlyViewdStoreTemplate.tsx
  src/components/template/recentlyViewedStoreTemplate.tsx
  src/components/template/storeDetailTemplate.tsx
  src/components/template/userTemplate.tsx
  src/components/template/writedReviewTemplate.tsx
  src/hooks/query.ts
  src/i18n.js
  src/types/coin.ts
  src/types/review.ts
  src/utils/array.ts
  src/utils/image.ts
Labels: enhancement, refactor

#121 버그 수정
  src/components/page/loginRedriect.tsx
  src/components/template/likedReviewTemplate.tsx
  src/setupProxy.js
Labels: bug

#122 리뷰 상세 페이지 이미지 문제 해결
  public/blankImages/profile.svg
  src/components/molecules/reviewInformation.tsx
  src/components/organisms/reviewImageCarousel.tsx
  src/types/review.ts
Labels: bug, refactor

#123 나와 비슷한 사용자에게 인기있는 음식점 추가
  src/apis/search.ts
  src/components/modals/searchModal.tsx
  src/i18n.js
Labels: enhancement

#119 사이트 자체 로그인, 회원가입
  package-lock.json
  package.json
  src/App.tsx
  src/apis/login.ts
  src/apis/profile.ts
  src/apis/register.ts
  src/components/atoms/icon.tsx
  src/components/atoms/input.tsx
  src/components/atoms/socialLoginButton.tsx
  src/components/layouts/login.tsx
  src/components/modals/modalContainer.tsx
  src/components/modals/socialLoginModalContent.tsx
  src/components/molecules/storeDetailHeader.tsx
  src/components/organisms/editProfileForm.tsx
  src/components/organisms/editProfileImage.tsx
  src/components/organisms/reviewImageCarousel.tsx
  src/components/page/login.tsx
  src/components/page/loginRedriect.tsx
  src/components/page/register.tsx
  src/components/page/registerUserInfoPage.tsx
  src/i18n.js
  src/store/index.ts
  src/store/slices/userProfileState.ts
  src/types/profile.ts
Labels: enhancement

#125 버그 수정
  src/apis/instance.ts
  src/components/molecules/reviewInformation.tsx
  src/components/molecules/storeDetailHeader.tsx
  src/components/template/coinRechargeTemplate.tsx
  src/components/template/coinUsageTemplate.tsx
  src/components/template/userTemplate.tsx
Labels: bug

#126 feat: 구글 지도 API 키 적용
  src/components/organisms/MyGoogleMap.tsx
Labels: enhancement

#127 번역 API 요청 주소 수정
  src/apis/translate.ts
Labels: bug

#130 README.md 수정 및 기타 버그 수정
  README.md
  k8s/configs/default.conf
  src/components/atoms/input.tsx
  src/components/molecules/menuTag.tsx
  src/components/page/writeReviewPage.tsx
  src/components/template/writeReviewTemplate.tsx
Labels: bug, documentation, enhancement

#135 api 관련 수정
  src/apis/profile.ts
  src/components/organisms/editProfileImage.tsx
Labels: Applied feedback
