Repository Step3-kakao-tech-campus/Team4_FE, pull requests merged in 2023-10, with the labels that each got.

#11 소셜 로그인 모달창 구현
  package-lock.json
  package.json
  public/img/social-login/google-logo.png
  public/img/social-login/kakao-ballon.png
  public/index.html
  src/App.tsx
  src/components/organisms/socialLoginModalContent.jsx
  src/components/socialLoginModal.jsx
  src/i18n.js
  tailwind.config.js
Labels: enhancement

#15 마이 페이지 UI 구현
  public/image/fakeDb/userPage/userImage.png
  src/App.tsx
  src/components/molecules/myPageList.tsx
  src/components/page/landingPage.tsx
  src/components/page/userPage.tsx
  src/components/template/userTemplate.tsx
  src/i18n.js
  src/react-app-env.d.ts
Labels: enhancement

#20 conflict 해결 중 발생한 오타 수정
  src/i18n.js
Labels: bug

#25 버튼 컴포넌트 구현
  .eslintrc.json
  src/components/atoms/button.tsx
Labels: enhancement

#26 input 컴포넌트 구현
  src/components/atoms/input.tsx
  src/types/refHandler.ts
Labels: enhancement

#29 이미지 최적화를 위한 컴포넌트 구현
  src/components/atoms/image.tsx
  src/i18n.js
Labels: enhancement

#31 feat: socialLoginButton 컴포넌트 구현
  src/App.tsx
  src/components/atoms/socialLoginButton.tsx
  src/components/organisms/socialLoginModalContent.jsx
  src/components/organisms/socialLoginModalContent.tsx
  src/i18n.js
Labels: enhancement

#33 메뉴 태그 컴포넌트 구현
  src/components/atoms/input.tsx
  src/components/molecules/menuTag.tsx
  src/i18n.js
Labels: enhancement

#35 음식점 카드 컴포넌트 구현
  src/components/atoms/image.tsx
  src/components/molecules/storeCard.tsx
  src/i18n.js
Labels: enhancement

#18 부산대 4조 MatGPT 4주차
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.test.tsx
  src/App.tsx
  src/components/atoms/button.tsx
  src/components/landingPage.tsx
  src/components/layouts/navigationBar.tsx
  src/components/molecules/radioOption.tsx
  src/components/organisms/optionSelectPopup.tsx
  src/i18n.js
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/types/option.ts
  src/utils/language.ts
  src/utils/modal.ts
  tailwind.config.js
  tsconfig.json
Labels: 리뷰 PR 제출

#42 페이지 제목 카드 구현
  src/components/molecules/pageTitleCard.tsx
  src/i18n.js
Labels: enhancement

#48 4주차 피드백 반영
  .eslintrc.json
  package-lock.json
  package.json
  src/components/atoms/button.tsx
  src/components/page/landingPage.tsx
  src/index.tsx
  src/test/reportWebVitals.ts
  src/test/setupTests.ts
  src/utils/localStorage.ts
  src/utils/modal.ts
Labels: Applied feedback

#47 feat: 리뷰 삭제 모달창 구현
  src/components/molecules/deleteReviewModal.tsx
  src/i18n.js
Labels: enhancement

#45 Feature/coin list card 코인 사용 내역 / 충전 내역 리스트 구현
  src/components/molecules/coinListCard.tsx
  src/utils/convert.ts
Labels: enhancement

#43 Feature/review card 리뷰카드 컴포넌트 구현
  public/image/fakeDb/reviewCard/storeImage.png
  public/image/fakeDb/reviewCard/userImage.png
  src/components/molecules/reviewCard.tsx
  src/i18n.js
Labels: enhancement

#49 메인 페이지 구현
  package-lock.json
  package.json
  public/image/fakeDb/store/store1.png
  public/image/fakeDb/store/store2.png
  public/image/fakeDb/store/store3.png
  public/index.html
  src/App.tsx
  src/components/molecules/marker.tsx
  src/components/molecules/searchBar.tsx
  src/components/molecules/storeCard.tsx
  src/components/organisms/MyGoogleMap.tsx
  src/components/page/landingPage.tsx
  src/components/page/mainPage.tsx
  src/i18n.js
  src/index.css
  src/types/map.ts
Labels: enhancement

#52 Feature/outlet layout 메인 레이아웃 구현 완료
  src/App.tsx
  src/components/layouts/mainLayout.tsx
  src/components/layouts/navigationBar.tsx
  src/components/page/mainPage.tsx
Labels: enhancement

#53 검색 결과 페이지 구현
  .eslintrc.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/instance.ts
  src/apis/search.ts
  src/components/molecules/storeCard.tsx
  src/components/page/searchResultPage.tsx
  src/components/template/searchResultTemplate.tsx
  src/hooks/intersectionObserver.ts
  src/hooks/query.ts
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/types/store.ts
  src/utils/fetch.ts
  src/utils/query.ts
Labels: enhancement

#55 config: 검색결과페이지 route 추가
  src/App.tsx
Labels: bug

#57 좋아요 한 페이지 UI, Mock api 연동 구현 완료
  src/App.tsx
  src/apis/likedStore.ts
  src/components/atoms/icon.tsx
  src/components/molecules/storeCard.tsx
  src/components/page/likedStorePage.tsx
  src/components/template/likedStoreTemplate.tsx
  src/components/template/userTemplate.tsx
  src/i18n.js
  src/mocks/handlers.ts
  src/types/store.ts
Labels: enhancement

#62 코인 충전 내역 페이지 UI, Mock api 연동 구현 완료
  src/App.tsx
  src/apis/coinCharge.ts
  src/components/molecules/coinListCard.tsx
  src/components/molecules/page.tsx
  src/components/page/coinRechargePage.tsx
  src/components/template/coinRechargeTemplate.tsx
  src/components/template/likedStoreTemplate.tsx
  src/components/template/userTemplate.tsx
  src/i18n.js
  src/mocks/handlers.ts
  src/types/coin.ts
  src/utils/convert.ts
Labels: enhancement

#66 최근에 본 맛집 페이지 UI, Mock api 연동 구현 완료
  src/App.tsx
  src/apis/getRecentlyViewdStore.ts
  src/components/page/recentlyViewdStorePage.tsx
  src/components/template/recentlyViewdStoreTemplate.tsx
  src/components/template/userTemplate.tsx
  src/i18n.js
  src/mocks/data/recentlyViewdStore.js
  src/mocks/handlers.ts
Labels: enhancement

#64 음식점 상세 페이지 구현
  src/App.tsx
  src/apis/storeDetail.ts
  src/components/atoms/icon.tsx
  src/components/molecules/storeDetailHeader.tsx
  src/components/organisms/storeDetailTab.tsx
  src/components/organisms/storeOverviewTab.tsx
  src/components/organisms/storeReviewTab.tsx
  src/components/page/storeDetailPage.tsx
  src/components/template/storeDetailTemplate.tsx
  src/hooks/query.ts
  src/i18n.js
  src/mocks/handlers.ts
  src/types/store.ts
Labels: enhancement

#72 모달 커스텀 hook 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/layouts/navigationBar.tsx
  src/components/modals/deleteReviewModal.tsx
  src/components/modals/languageModal.tsx
  src/components/modals/modalBackdrop.tsx
  src/components/modals/modalContainer.tsx
  src/components/modals/searchModal.tsx
  src/components/modals/socialLoginModalContent.tsx
  src/components/molecules/deleteReviewModal.tsx
  src/components/molecules/searchBar.tsx
  src/components/organisms/optionSelectPopup.tsx
  src/components/page/landingPage.tsx
  src/components/page/mainPage.tsx
  src/components/socialLoginModal.jsx
  src/hooks/modal.ts
  src/hooks/store.ts
  src/store/index.ts
  src/store/slices/modalSlice.ts
  src/types/modal.ts
  src/utils/modal.ts
Labels: enhancement

#73 5, 6주차 피드백 반영
  src/components/atoms/input.tsx
  src/components/molecules/imageCarousel.tsx
  src/components/molecules/menuTag.tsx
  src/components/molecules/myPageList.tsx
  src/components/molecules/page.tsx
  src/components/organisms/MyGoogleMap.tsx
  src/components/page/searchResultPage.tsx
  src/components/template/coinRechargeTemplate.tsx
  src/components/template/coinUsageTemlate.tsx
  src/components/template/likedReviewTemplate.tsx
  src/components/template/likedStoreTemplate.tsx
  src/components/template/recentlyViewdStoreTemplate.tsx
  src/components/template/writedReviewTemplate.tsx
  src/utils/localStorage.ts
Labels: enhancement, Applied feedback

#75 유저 정보 수정 페이지 구현
  src/App.tsx
  src/apis/profile.ts
  src/components/atoms/icon.tsx
  src/components/atoms/input.tsx
  src/components/molecules/dropdownList.tsx
  src/components/molecules/radioOption.tsx
  src/components/organisms/editProfileForm.tsx
  src/components/organisms/editProfileImage.tsx
  src/components/page/userEditProfilePage.tsx
  src/components/template/userEditProfileTeamplate.tsx
  src/components/template/userTemplate.tsx
  src/hooks/store.ts
  src/i18n.js
  src/mocks/handlers.ts
  src/store/index.ts
  src/store/slices/userProfileState.ts
  src/types/profile.ts
Labels: enhancement

#80 리뷰 작성 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/apis/review.ts
  src/components/atoms/icon.tsx
  src/components/atoms/input.tsx
  src/components/modals/imageCropModal.tsx
  src/components/molecules/menuTag.tsx
  src/components/molecules/selectRating.tsx
  src/components/molecules/selectTagRating.tsx
  src/components/molecules/tagRating.tsx
  src/components/organisms/uploadImage.tsx
  src/components/page/writeReviewPage.tsx
  src/components/template/writeReviewTemplate.tsx
  src/hooks/modal.ts
  src/hooks/query.ts
  src/hooks/store.ts
  src/i18n.js
  src/mocks/handlers.ts
  src/store/index.ts
  src/store/slices/menuTagSlice.ts
  src/types/refHandler.ts
  src/types/review.ts
  src/utils/cropImage.js
  src/utils/image.ts
Labels: enhancement

#84 메인 페이지 위치 기반 데이터 요청 구현
  src/apis/map.ts
  src/components/organisms/MyGoogleMap.tsx
  src/components/page/mainPage.tsx
  src/hooks/geolocation.ts
  src/mocks/data/storeMarker.js
  src/mocks/handlers.ts
  src/utils/fetchWithHandler.ts
  src/utils/geolocation.ts
Labels: enhancement

#86 리뷰 상세 페이지 구현
  public/image/fakeDb/review/reviewImage1.png
  public/image/fakeDb/review/reviewImage2.png
  src/App.tsx
  src/apis/prompt.ts
  src/apis/review.ts
  src/components/atoms/icon.tsx
  src/components/atoms/input.tsx
  src/components/molecules/imageCarousel.tsx
  src/components/molecules/menuTag.tsx
  src/components/molecules/promptList.tsx
  src/components/molecules/reviewInformation.tsx
  src/components/molecules/tagRating.tsx
  src/components/organisms/promptEdit.tsx
  src/components/organisms/reviewImageCarousel.tsx
  src/components/page/promptPage.tsx
  src/components/page/reviewDetailPage.tsx
  src/components/template/promptTemplate.tsx
  src/components/template/reviewDetailTemplate.tsx
  src/hooks/store.ts
  src/i18n.js
  src/mocks/data/prompts.js
  src/mocks/data/reviewDetailData.js
  src/mocks/handlers.ts
  src/store/index.ts
  src/types/review.ts
Labels: enhancement
