Repository Step3-kakao-tech-campus/Team4_FE, pull requests merged in 2023-09, with the labels that each got.

#1 Update issue templates
  .github/ISSUE_TEMPLATE/pr-풀리퀘스트-요청.md
  .github/ISSUE_TEMPLATE/기능-요청서.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
Labels: documentation

#6 랜딩 페이지 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/button.tsx
  src/components/landingPage.tsx
  src/components/molecules/radioOption.tsx
  src/components/organisms/optionSelectPopup.tsx
  src/i18n.js
  src/index.css
  src/types/option.ts
  src/utils/language.ts
  src/utils/modal.ts
  tailwind.config.js
Labels: enhancement

#8 하단 네비게이션 바 구현
  src/components/layouts/navigationBar.tsx
  src/i18n.js
Labels: enhancement

#9 페이지 방문 시 html lang 속성 바뀌지 않는 문제 해결
  .eslintrc.json
  src/components/landingPage.tsx
  src/i18n.js
  src/utils/language.ts
Labels: bug
